---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/21 下午6:00
---

local client = require("helper.http_client")

---@public
function test_get_method()
    res = client.get("http://101.200.184.102:7777/token/verify?token=QQuUa9RkZlSbY-9cc8USGSvLk_89lcEwGAz7xzUib6E",nil);
    print(res)
end

--执行测试
test_get_method();