---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午11:28
---

local response_error = require("helper.response_error");
local cjson = require("cjson");

print(cjson.encode(response_error.generate({})));

print("\\r\n");

print(cjson.encode(response_error.generate_error(300,"自定义错误")));


print("\\r\n");