---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午4:27
---
---@class table_helper
table_helper = {};

---@public empty_table
---@param tb table
---@return boolean
function table_helper.empty_table(tb)
    if tb == nil then
        return true;
    end

    --table 判断
    if type(tb) ~= "table" then
        return false;
    end

    return _G.next(tb) == nil;
end


return table_helper;