---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2019/1/4 下午12:54
---

local BaseLocation = require("src.location.base_location");



print("这是一个 测试")
_PROFILE1 = "debug1"
assert(_PROFILE1 == "debug");

return c;