---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/28 下午5:27
---

local cjson = require("cjson");

local json = {};
json.order_list = {};
json.order_list.page_index = 1;
json.order_list.page_size = 100;
json.order_list.data = {};

local data = {};
setmetatable(data,{ __newindex = json.order_list.data});

data[1] = {id=1,title="订单1",price=5.2,mobile="13633898976"};
data[2] = {id=2,title="订单2",price=5.6,mobile="13633898977"};
data[3] = {id=3,title="订单3",price=5.8,mobile="13633898978"};


print(cjson.encode(json));


local rapidjson = require("rapidjson");

local d = rapidjson.Document(json)
--assert(d:get('/json/order_list/page_index') == 1)
d:set('/order_list/data/*/mobile', '1')

print(cjson.encode(json.order_list.data));
