---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午4:54
---

local metatb = { name = "metatb", age = 256};
local newtn = {};
setmetatable(newtn,metatb);
print(newtn.name)
print(newtn.age)

newtn.name = "newtn";
newtn.age = 512;
print(newtn.name)
print(newtn.age)


local mtb = getmetatable(newtn)
print(mtb.name)
print(mtb.age)



function getTodayTimeStamp()
    local cDateCurrectTime = os.date("*t");

    local cDateTodayTime = os.time({year=cDateCurrectTime.year, month=cDateCurrectTime.month, day=cDateCurrectTime.day, hour=23,min=59,sec=59});

    return cDateTodayTime
end

print(getTodayTimeStamp())
