---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/24 下午4:47
---
local count = 0;
local function f_increase()
    count = count + 1;
    ngx.say("count : ", count);
end
---@class _MODULE_CACHE
local _MODULE_CACHE = {}

-- function
_MODULE_CACHE.f_increase = f_increase;

return _MODULE_CACHE;