---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午5:53
---
local jwt_service = require("src.service.jwt_service");
local conf = require("src.conf.octo_conf");

--4、进行代理 a、octo—token生成
local path = "/v1/auth"
local request_uri = ngx.var.request_uri;
local target_uri = string.sub(request_uri,string.len(path) + 1);
local proxy_addr =conf.server.."/auth";
local url  = proxy_addr..target_uri;

--set token
ngx.req.set_header("Authorization", "Bearer "..jwt_service.get_jwt_token());

--5、执行子链接，并捕获信息。
local res = ngx.location.capture('/internet_proxy',
        {
            args = {url = url },
            copy_all_vars = true
        }
)

--5、返回代理response
ngx.print(res.body)