---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2019/1/4 下午12:14
---
---@deprecated
local Object = require "src.vendor.classic";
local BaseLocation = Object:extend();

--实例化
function BaseLocation:new(name)
    self._name = name
end

return BaseLocation;