---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午5:59
---@class
_DEBUG();
--执行
local jwt_service = require("src.service.jwt_service");
ngx.say(jwt_service.get_jwt_token());
