---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2019/5/31 下午5:01
---

local cityTimeService = require("src.service.city_time_service")

local time = cityTimeService.getTimeFromCIty("许昌")
if time then
    --- 返回结果
    ngx.say("result #1: ", cjson.encode(time));
else
    ngx.say("result is empty");
end
