---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午5:19
---
_DEBUG();
--initial
if ngx.shared.ngx_cache == nil then
    ngx.shared.ngx_cache = {};
end


ngx.print(cjson.encode(ngx.shared.ngx_cache));
local user = ngx.shared.ngx_cache;

local value, _ = ngx.shared.ngx_cache:get("name")
if value == nil then
    ngx.print("获取姓名为空，写入姓名：".."resty");
    user:set("name","resty");
    ngx.print("写入姓名成功".."resty");
else
   ngx.print("获取姓名："..value);
end

ngx.print(cjson.encode(ngx.shared.ngx_cache));

