---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午11:15
---
---@class response_error
response_error = {};

local time_helper = require("src.helper.time_helper");
local table_helper = require("src.helper.table_helper");

---@private base_error
---@return table
local function base_error()
    local metatable = {
        version = 0,
        status = 0,
        err_msg = "ok",
        error_msg = "ok",
        data = nil
    };
    return metatable;
end


function response_error:new()
    local obj = {};
    setmetatable(obj, self);
    -- 设置元表查找
    self.__index = self;
    --返回当前对象（面向对象开发）
    return obj;
end

---@public generate
---@param error_tb table
---@return table
function response_error:generate(error_tb)
    local tb = {};
    local metatable = base_error();
    setmetatable(tb,{__newindex = metatable});
    tb.ts = time_helper.current_time_millis();
    -- 空返回正确
    if table_helper.empty_table(error_tb) then
        return metatable;
    end

    tb.status = error_tb.code;
    tb.err_msg = error_tb.err_msg;
    tb.error_msg = error_tb.error_msg;
    return metatable;
end


---@public generate_error
---@param code number
---@param message string
---@return table
function response_error:generate_error(code,message)
    local tb = {};
    local metatable = base_error();
    setmetatable(tb,{__newindex = metatable});
    tb.status = code;
    tb.err_msg = message;
    tb.error_msg = message;
    tb.ts = time_helper.current_time_millis();
    return metatable;
end

return response_error;