---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午3:13
---

local white_list = require("conf.white_list_conf")


print(white_list.have_authority("","/v0/auth/users"));
print(white_list.have_authority(nil,"/v0/auth/users"));
print(white_list.have_authority("SALESManager","/v0/auth/users"));
print(white_list.have_authority("FIELDSALEManager","/v0/auth/ucities"));
print(white_list.have_authority("SALESManager","/v0/auth/test"));
print(white_list.have_authority("SALESManager","/v0/auth/test1"));
print(white_list.have_authority("SALESManager","/v0/auth/test2"));
print(white_list.have_authority("SALESManager","/v0/auth/test3"));



print(white_list.match_logic.OR)