---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午5:53
---
local jwt_service = require("service.jwt_service");
local conf = require("conf.octo_conf");
local string = require("string");
local table_helper = require("helper.table_helper");
local authority_service = require("service.authority_service");
local cjson = require("cjson");
local response_error = require("helper.response_error");

--[[
    ngx.ctx[name] 贯穿整个location生命周期，跳转到其他location就会失效
]]
--请求进入初始化
local response= response_error:new();
--[[
    权限判断 app-api
]]
local request_args_tab = ngx.req.get_uri_args();
--1、参数为空 直接返回没有权限
if table_helper.empty_table(request_args_tab) then
    ngx.status = ngx.HTTP_UNAUTHORIZED;
    ngx.print(cjson.encode(response:generate_error(401,"uri参数中没有设置app_token！")));
    return;
end

--2、判断参数中是否包含app_token
local app_token = request_args_tab["app_token"];
if app_token == nil or app_token == "" then
    ngx.status = ngx.HTTP_UNAUTHORIZED;
    ngx.print(cjson.encode(response:generate_error(401,"uri参数中没有设置app_token！")));
    return;
end

--3、进行mas校验返回用户权限；
local uri = ngx.var.uri;
local result = authority_service.verify_user_authority(uri,app_token);
if result.status ~= 0 then
    ngx.status = ngx.HTTP_UNAUTHORIZED;
    ngx.print(cjson.encode(result));
    return;
end


--4、进行代理 a、octo—token生成
local path = "/v0/auth"
local request_uri = ngx.var.request_uri;
local target_uri = string.sub(request_uri,string.len(path) + 1);
local proxy_addr =conf.server.."/auth";
local url  = proxy_addr..target_uri;

--set token
ngx.req.set_header("Authorization", "Bearer "..jwt_service.get_jwt_token());

--4、进行代理 a、代理连接
local res = ngx.location.capture('/internet_proxy',
        {
            args = {url = url },
            copy_all_vars = true
        }
)

--5、返回代理response
ngx.print(res.body)