---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午5:59
---
local jwt_service = require("service.jwt_service");

ngx.say(jwt_service.get_jwt_token());