---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午4:41
---
local module_cache = require("service.module_cache_service");
module_cache.f_increase();