---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/24 下午7:57
---

--[[
    公共包引用的范围为http块；项目用到的非配置类都可以在此处配置；
    日志级别：
   ngx.STDERR
   ngx.EMERG
   ngx.ALERT
   ngx.CRIT
   ngx.ERR
   ngx.WARN
   ngx.NOTICE
   ngx.INFO
   ngx.DEBUG
]]
-- 加载cjson
cjson = require("cjson");
-- 加载string
string = require("string");

--[[
   项目内公共包配置
]]
-- 加载resty.core
require("resty.core");


--[[
    描述：加载环境配置
]]
_PROFILE = "testing";
local profile_arr = {};
local profiles = {
    debug = true,
    testing = true,
    production = true
};

for k in pairs(profiles) do
    profile_arr[#profile_arr+1] = k
end
--排序
table.sort(profile_arr);
local help = string.format([[
Usage: light-api profiles

The available profiles are:
 %s
]], table.concat(profile_arr, "\n "));

--启动配置
return function(args)
    -- 处理参数
    local cmd_name = table.remove(args, 1)
    if not cmd_name then
        ngx.log(ngx.ALERT,help);
        return;
    elseif not profiles[cmd_name] then
        ngx.log(ngx.ALERT,help);
        return;
    end

    _PROFILE = cmd_name;
    ngx.log(ngx.ALERT,string.format([[
        The profile is %s .]],_PROFILE));
end
