---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2019/5/31 下午5:30
---

mysql_conf = {_VERSION="0.1.0"};

--- 默认
mysql_conf.defaultSource = "default";

---获取配置文件
local function get_conf()
    if _PROFILE == "debug" then
        --debug 环境
        local config = {
            default = { -- your connection name
                host = "127.0.0.1",
                port = 3306,
                database = "test",
                username = "root",
                password = "Aa@12345",
                poolSize = 50,
                maxIdleTimeout = 10000,  --- 10 sec
                timeout = 3000, -- millisecond watch out this value
            }
        }
        --返回配置
        return config;
    elseif _PROFILE == "testing" then
        --testing 环境
        local config = {
            default = { -- your connection name
                host = "127.0.0.1",
                port = 3306,
                database = "test",
                username = "root",
                password = "Aa@12345",
                poolSize = 50,
                maxIdleTimeout = 10000,  --- 10 sec
                timeout = 3000, -- millisecond watch out this value
            }
        }
        --返回配置
        return config;
    elseif _PROFILE == "production" then
        --production 环境
        default = { -- your connection name
            host = "127.0.0.1",
            port = 3306,
            database = "test",
            username = "root",
            password = "Aa@12345",
            poolSize = 50,
            maxIdleTimeout = 10000,  --- 10 sec
            timeout = 3000, -- millisecond watch out this value
        }
        --返回配置
        return config;
    end
    return nil;
end

-- 获取配置信息
function mysql_conf.config(dataSource)
    local config = get_conf();
    if dataSource == "default" or dataSource == nil then
        return config.default;
    elseif dataSource == "slave1" then
        --- todo
        return config.default
    else
        --- todo
        return config.default;
    end
end

return mysql_conf;




