---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2019/1/4 下午1:58
---
function _DEBUG()
    if _PROFILE == "debug" then
        require("mobdebug").start();
    end
end