---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午2:22
---

local cjson = require("cjson");

ngx.header.content_type = "text/plain";
local user = ngx.shared.ngx_cache;

if user:get("name") == nil then
    ngx.print("初始化...");
    user:set("name","dict");
    ngx.print("stored");
end


ngx.print(user:get("name"));


ngx.print("---------------\r\n");


if ngx.shared.ngx_cache.order == nil then
    ngx.print("order is nil")
    --初始化空表
    ngx.shared.ngx_cache.order = {};
end

local order = {}
setmetatable(order,{__newindex = ngx.shared.ngx_cache.order , __index = ngx.shared.ngx_cache.order});


order.conf = "this is page";
ngx.print("---------------\r\n");
ngx.print(order["conf"]);
ngx.print("---------------\r\n");
local tt = ngx.shared.ngx_cache.order
ngx.print(cjson.encode(tt));