---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/22 下午9:53
---


local redis_service = require("service.redis_service");

ngx.header.content_type = "text/plain";

redis_service.set("test_name","111111");

ngx.print(redis_service.get("test_name"));

ngx.print("\\r\n");

local response_error = require("helper.response_error");
local cjson = require("cjson");

local respose = response_error:new();
ngx.print(cjson.encode(respose:generate({})));

ngx.print("\\r\n");

ngx.print(cjson.encode(respose:generate_error(300,"自定义错误")));


ngx.print("\\r\n");

ngx.print(cjson.encode(respose:generate(nil)));
